# Generated by Django 4.2.7 on 2026-05-18 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('game', models.CharField(choices=[('FIFA', 'EA FC (FIFA)'), ('COD', 'Call of Duty'), ('TEKKEN', 'Tekken 8'), ('SF6', 'Street Fighter 6'), ('KI', 'Killer Instinct'), ('FH6', 'Forza Horizon 6')], max_length=20)),
                ('description', models.TextField()),
                ('format', models.CharField(choices=[('single_elimination', 'Single Elimination'), ('double_elimination', 'Double Elimination'), ('round_robin', 'Round Robin'), ('swiss', 'Swiss System'), ('group_stage', 'Group Stage + Playoffs')], default='single_elimination', max_length=30)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('max_participants', models.PositiveIntegerField(default=16)),
                ('prize_pool', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='league_banners/')),
                ('rules', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_leagues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_p1', models.PositiveIntegerField(default=0)),
                ('score_p2', models.PositiveIntegerField(default=0)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('played_at', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='leagues.league')),
                ('player_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p1', to=settings.AUTH_USER_MODEL)),
                ('player_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_p2', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['round_number', 'played_at'],
            },
        ),
        migrations.CreateModel(
            name='LeagueRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='leagues.league')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'League Registration',
                'verbose_name_plural': 'League Registrations',
                'unique_together': {('league', 'player')},
            },
        ),
    ]
